Add sign up cancellation and position management
akimich11/dma-bmi-bot pull request #9
Opened 2021-11-03 17:24 UTC by elizabethfeden

Теперь можно делать:
* `/sign_up subject date pos`, чтобы записаться на конкретное место
* `/sign_up subject date`, чтобы записаться в конец
* `/move subject date pos`, если ты уже в очереди, но хочешь переместиться на другое пустое место
* `/cancel_sign_up subject date`, если ты передумал 

В плане менеджмента позиций можно конечно еще добавлять всякие свапы и рандомизации очередей, но вообще-то для этого другой бот есть, ну и это короче как нибудь потом

2021-11-03 18:47 UTC, akimich11 requested changes

2021-11-03 18:47 UTC, akimich11 commented on queues/models.py
> +        return self.sign_up(date, subject, user_id, new_pos)
Наверное лучше другое сообщение выводить, либо в сообщении о добавлении в очередь выводить место в этой очереди

2021-11-03 18:47 UTC, akimich11 commented on queues/models.py
>              return f'{self.date}, {self.subject}\nОчередь:\n' +\
хз почему код не падает при бэкслеше в f-строке, по идее они запрещены

2021-11-03 18:47 UTC, akimich11 commented on queues/models.py
>                              (pickle.dumps(queue.queue), queue.subject, queue.date))
ну тут надо менять это чудо, чтоб позиции сохраняло в базу

2021-11-03 20:06 UTC, elizabethfeden commented on queues/models.py
> +                return 'Похоже, кто-то уже занял самое последнее место.'
блин реально токсично выглядит, уберу пожалуй)

2021-11-03 20:11 UTC, elizabethfeden commented on queues/models.py
> +        return self.sign_up(date, subject, user_id, new_pos)
я это чуток костыльно сделаю, чтобы не ломать предыдущее не самое архитектурно идеальное решение о том, что если функция возвращает None, то все хорошо

но сделаю)

2021-11-03 20:12 UTC, elizabethfeden commented on queues/models.py
>              return f'{self.date}, {self.subject}\nОчередь:\n' +\
начнем с того, что это твой код :D
ну и по идее не запрещены

2021-11-03 20:12 UTC, elizabethfeden commented on queues/models.py
>                              (pickle.dumps(queue.queue), queue.subject, queue.date))
теперь работает

2021-11-04 15:50 UTC, akimich11 reviewed
Ну короч надо сериализацию `id_to_pos` сделать и убрать везде поле `date`, когда сделаю апрувну PR

2021-11-04 15:50 UTC, akimich11 commented on queues/models.py
> +                              if user_id != self.EMPTY}
Это уже лучше, но по-прежнему раз в день нумерация в очереди будет сбиваться (если стояла какая-то кастомная), потому что бот перезапускается. Короч, я потом сам сериализую `id_to_pos` в базу, это можешь не трогать

2021-11-04 16:37 UTC, akimich11 approved these changes
Looks pretty good, let's test on production :)

2021-11-04 16:38 UTC, merged